.PHONY: lint
lint:
	go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
	golangci-lint run

.PHONY: generate
generate:
	go install golang.org/x/tools/cmd/stringer@latest
	go generate ./...
